name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: bootstap
      run: ./bootstrap.sh

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make dist 

    - name: Upload dist to Release
      uses: svenstaro/upload-release-action@2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: obstack-*.tar.gz
        tag: ${{ github.ref }}
        file_glob: true
