name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: bootstap
      run: ./bootstrap.sh

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make dist 

    - name: Upload dist to Release
      uses: actions/upload-artifact@v4
        name: musl-obstack.tar.gz 
        path: *.tar.gz
        
